# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SR830.ui'
#
# Created: Wed Oct 08 14:01:28 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(854, 283)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 131, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.tauval = QtGui.QComboBox(self.groupBox)
        self.tauval.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.tauval.setObjectName(_fromUtf8("tauval"))
        self.tauval.addItem(_fromUtf8(""))
        self.tauval.addItem(_fromUtf8(""))
        self.tauval.addItem(_fromUtf8(""))
        self.tauval.addItem(_fromUtf8(""))
        self.tauval.addItem(_fromUtf8(""))
        self.tauval.addItem(_fromUtf8(""))
        self.tauunit = QtGui.QComboBox(self.groupBox)
        self.tauunit.setGeometry(QtCore.QRect(50, 20, 41, 20))
        self.tauunit.setObjectName(_fromUtf8("tauunit"))
        self.tauunit.addItem(_fromUtf8(""))
        self.tauunit.addItem(_fromUtf8(""))
        self.tauunit.addItem(_fromUtf8(""))
        self.tauunit.addItem(_fromUtf8(""))
        self.slopeval = QtGui.QComboBox(self.groupBox)
        self.slopeval.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.slopeval.setObjectName(_fromUtf8("slopeval"))
        self.slopeval.addItem(_fromUtf8(""))
        self.slopeval.addItem(_fromUtf8(""))
        self.slopeval.addItem(_fromUtf8(""))
        self.slopeval.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(60, 50, 21, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.synccheck = QtGui.QCheckBox(self.groupBox)
        self.synccheck.setGeometry(QtCore.QRect(10, 80, 91, 17))
        self.synccheck.setObjectName(_fromUtf8("synccheck"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 10, 120, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.sensval = QtGui.QComboBox(self.groupBox_2)
        self.sensval.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.sensval.setObjectName(_fromUtf8("sensval"))
        self.sensval.addItem(_fromUtf8(""))
        self.sensval.addItem(_fromUtf8(""))
        self.sensval.addItem(_fromUtf8(""))
        self.sensval.addItem(_fromUtf8(""))
        self.sensval.addItem(_fromUtf8(""))
        self.sensval.addItem(_fromUtf8(""))
        self.sensval.addItem(_fromUtf8(""))
        self.sensval.addItem(_fromUtf8(""))
        self.sensval.addItem(_fromUtf8(""))
        self.sensunit = QtGui.QComboBox(self.groupBox_2)
        self.sensunit.setGeometry(QtCore.QRect(50, 20, 51, 20))
        self.sensunit.setObjectName(_fromUtf8("sensunit"))
        self.sensunit.addItem(_fromUtf8(""))
        self.sensunit.addItem(_fromUtf8(""))
        self.sensunit.addItem(_fromUtf8(""))
        self.sensunit.addItem(_fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 120, 131, 81))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 41, 41))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.input = QtGui.QComboBox(self.verticalLayoutWidget)
        self.input.setObjectName(_fromUtf8("input"))
        self.input.addItem(_fromUtf8(""))
        self.input.addItem(_fromUtf8(""))
        self.input.addItem(_fromUtf8(""))
        self.input.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.input)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 40, 42, 41))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.coupling = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.coupling.setObjectName(_fromUtf8("coupling"))
        self.coupling.addItem(_fromUtf8(""))
        self.coupling.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.coupling)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(80, 40, 52, 41))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.ground = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.ground.setMinimumSize(QtCore.QSize(50, 0))
        self.ground.setObjectName(_fromUtf8("ground"))
        self.ground.addItem(_fromUtf8(""))
        self.ground.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.ground)
        self.ovldcheck = QtGui.QCheckBox(self.groupBox_3)
        self.ovldcheck.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.ovldcheck.setObjectName(_fromUtf8("ovldcheck"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(150, 70, 120, 61))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.reserveset = QtGui.QComboBox(self.groupBox_4)
        self.reserveset.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.reserveset.setObjectName(_fromUtf8("reserveset"))
        self.reserveset.addItem(_fromUtf8(""))
        self.reserveset.addItem(_fromUtf8(""))
        self.reserveset.addItem(_fromUtf8(""))
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(150, 140, 120, 61))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.filterset = QtGui.QComboBox(self.groupBox_5)
        self.filterset.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.filterset.setObjectName(_fromUtf8("filterset"))
        self.filterset.addItem(_fromUtf8(""))
        self.filterset.addItem(_fromUtf8(""))
        self.filterset.addItem(_fromUtf8(""))
        self.filterset.addItem(_fromUtf8(""))
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(280, 80, 171, 131))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 51, 41))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.ch1_disp = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.ch1_disp.setObjectName(_fromUtf8("ch1_disp"))
        self.ch1_disp.addItem(_fromUtf8(""))
        self.ch1_disp.addItem(_fromUtf8(""))
        self.ch1_disp.addItem(_fromUtf8(""))
        self.ch1_disp.addItem(_fromUtf8(""))
        self.ch1_disp.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.ch1_disp)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(60, 20, 51, 41))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.ch1_ratio = QtGui.QComboBox(self.verticalLayoutWidget_5)
        self.ch1_ratio.setObjectName(_fromUtf8("ch1_ratio"))
        self.ch1_ratio.addItem(_fromUtf8(""))
        self.ch1_ratio.addItem(_fromUtf8(""))
        self.ch1_ratio.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.ch1_ratio)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(110, 20, 52, 41))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_6.addWidget(self.label_7)
        self.ch1_expand = QtGui.QComboBox(self.verticalLayoutWidget_6)
        self.ch1_expand.setObjectName(_fromUtf8("ch1_expand"))
        self.ch1_expand.addItem(_fromUtf8(""))
        self.ch1_expand.addItem(_fromUtf8(""))
        self.ch1_expand.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.ch1_expand)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(60, 70, 60, 41))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_7.addWidget(self.label_8)
        self.ch1_offset = QtGui.QComboBox(self.verticalLayoutWidget_7)
        self.ch1_offset.setObjectName(_fromUtf8("ch1_offset"))
        self.ch1_offset.addItem(_fromUtf8(""))
        self.ch1_offset.addItem(_fromUtf8(""))
        self.ch1_offset.addItem(_fromUtf8(""))
        self.ch1_offset.addItem(_fromUtf8(""))
        self.verticalLayout_7.addWidget(self.ch1_offset)
        self.groupBox_8 = QtGui.QGroupBox(Dialog)
        self.groupBox_8.setGeometry(QtCore.QRect(450, 210, 191, 61))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.AutoPhaseButton = QtGui.QPushButton(self.groupBox_8)
        self.AutoPhaseButton.setGeometry(QtCore.QRect(10, 20, 51, 23))
        self.AutoPhaseButton.setObjectName(_fromUtf8("AutoPhaseButton"))
        self.AutoGainButton = QtGui.QPushButton(self.groupBox_8)
        self.AutoGainButton.setGeometry(QtCore.QRect(70, 20, 51, 23))
        self.AutoGainButton.setObjectName(_fromUtf8("AutoGainButton"))
        self.ReserveButton = QtGui.QPushButton(self.groupBox_8)
        self.ReserveButton.setGeometry(QtCore.QRect(130, 20, 51, 23))
        self.ReserveButton.setObjectName(_fromUtf8("ReserveButton"))
        self.Channel1 = QtGui.QLCDNumber(Dialog)
        self.Channel1.setGeometry(QtCore.QRect(280, 10, 171, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.Channel1.setPalette(palette)
        self.Channel1.setNumDigits(9)
        self.Channel1.setObjectName(_fromUtf8("Channel1"))
        self.Channel2 = QtGui.QLCDNumber(Dialog)
        self.Channel2.setGeometry(QtCore.QRect(460, 10, 181, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.Channel2.setPalette(palette)
        self.Channel2.setNumDigits(9)
        self.Channel2.setObjectName(_fromUtf8("Channel2"))
        self.Ref = QtGui.QLCDNumber(Dialog)
        self.Ref.setGeometry(QtCore.QRect(650, 10, 181, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.Ref.setPalette(palette)
        self.Ref.setNumDigits(7)
        self.Ref.setObjectName(_fromUtf8("Ref"))
        self.groupBox_9 = QtGui.QGroupBox(Dialog)
        self.groupBox_9.setGeometry(QtCore.QRect(650, 80, 191, 131))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.reference = QtGui.QComboBox(self.groupBox_9)
        self.reference.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.reference.setObjectName(_fromUtf8("reference"))
        self.reference.addItem(_fromUtf8(""))
        self.reference.addItem(_fromUtf8(""))
        self.reference.addItem(_fromUtf8(""))
        self.reference.addItem(_fromUtf8(""))
        self.phaesplus90 = QtGui.QPushButton(self.groupBox_9)
        self.phaesplus90.setGeometry(QtCore.QRect(10, 50, 51, 23))
        self.phaesplus90.setObjectName(_fromUtf8("phaesplus90"))
        self.phasemin90 = QtGui.QPushButton(self.groupBox_9)
        self.phasemin90.setGeometry(QtCore.QRect(60, 50, 51, 23))
        self.phasemin90.setObjectName(_fromUtf8("phasemin90"))
        self.verticalLayoutWidget_12 = QtGui.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 80, 61, 41))
        self.verticalLayoutWidget_12.setObjectName(_fromUtf8("verticalLayoutWidget_12"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_12)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_12.addWidget(self.label_13)
        self.trigshape = QtGui.QComboBox(self.verticalLayoutWidget_12)
        self.trigshape.setObjectName(_fromUtf8("trigshape"))
        self.trigshape.addItem(_fromUtf8(""))
        self.trigshape.addItem(_fromUtf8(""))
        self.trigshape.addItem(_fromUtf8(""))
        self.verticalLayout_12.addWidget(self.trigshape)
        self.verticalLayoutWidget_13 = QtGui.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(70, 80, 66, 41))
        self.verticalLayoutWidget_13.setObjectName(_fromUtf8("verticalLayoutWidget_13"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_13)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_13.addWidget(self.label_14)
        self.trigsource = QtGui.QComboBox(self.verticalLayoutWidget_13)
        self.trigsource.setObjectName(_fromUtf8("trigsource"))
        self.trigsource.addItem(_fromUtf8(""))
        self.trigsource.addItem(_fromUtf8(""))
        self.verticalLayout_13.addWidget(self.trigsource)
        self.setRefbutton = QtGui.QPushButton(self.groupBox_9)
        self.setRefbutton.setGeometry(QtCore.QRect(150, 50, 31, 23))
        self.setRefbutton.setObjectName(_fromUtf8("setRefbutton"))
        self.newrefval = QtGui.QLineEdit(self.groupBox_9)
        self.newrefval.setGeometry(QtCore.QRect(130, 20, 51, 20))
        self.newrefval.setObjectName(_fromUtf8("newrefval"))
        self.groupBox_7 = QtGui.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(460, 80, 171, 131))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 51, 41))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_8)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_8.addWidget(self.label_9)
        self.ch2_disp = QtGui.QComboBox(self.verticalLayoutWidget_8)
        self.ch2_disp.setObjectName(_fromUtf8("ch2_disp"))
        self.ch2_disp.addItem(_fromUtf8(""))
        self.ch2_disp.addItem(_fromUtf8(""))
        self.ch2_disp.addItem(_fromUtf8(""))
        self.ch2_disp.addItem(_fromUtf8(""))
        self.ch2_disp.addItem(_fromUtf8(""))
        self.verticalLayout_8.addWidget(self.ch2_disp)
        self.verticalLayoutWidget_9 = QtGui.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(60, 20, 51, 41))
        self.verticalLayoutWidget_9.setObjectName(_fromUtf8("verticalLayoutWidget_9"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_9)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_9.addWidget(self.label_10)
        self.ch2_ratio = QtGui.QComboBox(self.verticalLayoutWidget_9)
        self.ch2_ratio.setObjectName(_fromUtf8("ch2_ratio"))
        self.ch2_ratio.addItem(_fromUtf8(""))
        self.ch2_ratio.addItem(_fromUtf8(""))
        self.ch2_ratio.addItem(_fromUtf8(""))
        self.verticalLayout_9.addWidget(self.ch2_ratio)
        self.verticalLayoutWidget_10 = QtGui.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(110, 20, 52, 41))
        self.verticalLayoutWidget_10.setObjectName(_fromUtf8("verticalLayoutWidget_10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_10)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_10.addWidget(self.label_11)
        self.ch2_expand = QtGui.QComboBox(self.verticalLayoutWidget_10)
        self.ch2_expand.setObjectName(_fromUtf8("ch2_expand"))
        self.ch2_expand.addItem(_fromUtf8(""))
        self.ch2_expand.addItem(_fromUtf8(""))
        self.ch2_expand.addItem(_fromUtf8(""))
        self.verticalLayout_10.addWidget(self.ch2_expand)
        self.verticalLayoutWidget_11 = QtGui.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(60, 70, 60, 41))
        self.verticalLayoutWidget_11.setObjectName(_fromUtf8("verticalLayoutWidget_11"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_11)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_11.addWidget(self.label_12)
        self.ch2_offset = QtGui.QComboBox(self.verticalLayoutWidget_11)
        self.ch2_offset.setObjectName(_fromUtf8("ch2_offset"))
        self.ch2_offset.addItem(_fromUtf8(""))
        self.ch2_offset.addItem(_fromUtf8(""))
        self.ch2_offset.addItem(_fromUtf8(""))
        self.ch2_offset.addItem(_fromUtf8(""))
        self.verticalLayout_11.addWidget(self.ch2_offset)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.AutoPhaseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.autophase)
        QtCore.QObject.connect(self.AutoGainButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.autogain)
        QtCore.QObject.connect(self.ReserveButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.autoreserve)
        QtCore.QObject.connect(self.setRefbutton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.setRef)
        QtCore.QObject.connect(self.phaesplus90, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.phaseplus)
        QtCore.QObject.connect(self.phasemin90, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.phasemin)
        QtCore.QObject.connect(self.tauval, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgtau)
        QtCore.QObject.connect(self.tauunit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgtau)
        QtCore.QObject.connect(self.sensval, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgsens)
        QtCore.QObject.connect(self.sensunit, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgsens)
        QtCore.QObject.connect(self.reserveset, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgres)
        QtCore.QObject.connect(self.slopeval, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgslope)
        QtCore.QObject.connect(self.synccheck, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Dialog.chgsync)
        QtCore.QObject.connect(self.input, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.selinput)
        QtCore.QObject.connect(self.coupling, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.selcoup)
        QtCore.QObject.connect(self.ground, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.selgnd)
        QtCore.QObject.connect(self.filterset, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgfilt)
        QtCore.QObject.connect(self.ch1_disp, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgch1disp)
        QtCore.QObject.connect(self.ch1_ratio, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgch1ratio)
        QtCore.QObject.connect(self.ch1_expand, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgch1expand)
        QtCore.QObject.connect(self.ch1_offset, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgch1offset)
        QtCore.QObject.connect(self.ch2_disp, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgch2disp)
        QtCore.QObject.connect(self.ch2_ratio, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgch2ratio)
        QtCore.QObject.connect(self.ch2_expand, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgch2expand)
        QtCore.QObject.connect(self.ch2_offset, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgch2offset)
#        QtCore.QObject.connect(self.reference, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgref)
        QtCore.QObject.connect(self.trigshape, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgtrigshape)
        QtCore.QObject.connect(self.trigsource, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.chgtrigsource)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Time Constant", None))
        self.tauval.setItemText(0, _translate("Dialog", "1", None))
        self.tauval.setItemText(1, _translate("Dialog", "3", None))
        self.tauval.setItemText(2, _translate("Dialog", "10", None))
        self.tauval.setItemText(3, _translate("Dialog", "30", None))
        self.tauval.setItemText(4, _translate("Dialog", "100", None))
        self.tauval.setItemText(5, _translate("Dialog", "300", None))
        self.tauunit.setItemText(0, _translate("Dialog", "ks", None))
        self.tauunit.setItemText(1, _translate("Dialog", "s", None))
        self.tauunit.setItemText(2, _translate("Dialog", "ms", None))
        self.tauunit.setItemText(3, _translate("Dialog", "mus", None))
        self.slopeval.setItemText(0, _translate("Dialog", "6", None))
        self.slopeval.setItemText(1, _translate("Dialog", "12", None))
        self.slopeval.setItemText(2, _translate("Dialog", "18", None))
        self.slopeval.setItemText(3, _translate("Dialog", "24", None))
        self.label_4.setText(_translate("Dialog", "db", None))
        self.synccheck.setText(_translate("Dialog", "Sync <200 Hz", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Sensitivity", None))
        self.sensval.setItemText(0, _translate("Dialog", "1", None))
        self.sensval.setItemText(1, _translate("Dialog", "2", None))
        self.sensval.setItemText(2, _translate("Dialog", "5", None))
        self.sensval.setItemText(3, _translate("Dialog", "10", None))
        self.sensval.setItemText(4, _translate("Dialog", "20", None))
        self.sensval.setItemText(5, _translate("Dialog", "50", None))
        self.sensval.setItemText(6, _translate("Dialog", "100", None))
        self.sensval.setItemText(7, _translate("Dialog", "200", None))
        self.sensval.setItemText(8, _translate("Dialog", "500", None))
        self.sensunit.setItemText(0, _translate("Dialog", "V", None))
        self.sensunit.setItemText(1, _translate("Dialog", "mV", None))
        self.sensunit.setItemText(2, _translate("Dialog", "muV", None))
        self.sensunit.setItemText(3, _translate("Dialog", "nV", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Signal Input", None))
        self.label.setText(_translate("Dialog", "Input", None))
        self.input.setItemText(0, _translate("Dialog", "A", None))
        self.input.setItemText(1, _translate("Dialog", "A-B", None))
        self.input.setItemText(2, _translate("Dialog", "I(10^6)", None))
        self.input.setItemText(3, _translate("Dialog", "I(10^8)", None))
        self.label_2.setText(_translate("Dialog", "Couple", None))
        self.coupling.setItemText(0, _translate("Dialog", "AC", None))
        self.coupling.setItemText(1, _translate("Dialog", "DC", None))
        self.label_3.setText(_translate("Dialog", "Ground", None))
        self.ground.setItemText(0, _translate("Dialog", "Float", None))
        self.ground.setItemText(1, _translate("Dialog", "Ground", None))
        self.ovldcheck.setText(_translate("Dialog", "OVLD", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Reserve", None))
        self.reserveset.setItemText(0, _translate("Dialog", "High Reserve", None))
        self.reserveset.setItemText(1, _translate("Dialog", "Normal", None))
        self.reserveset.setItemText(2, _translate("Dialog", "Low Noise", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Filters", None))
        self.filterset.setItemText(0, _translate("Dialog", "None", None))
        self.filterset.setItemText(1, _translate("Dialog", "Line", None))
        self.filterset.setItemText(2, _translate("Dialog", "2 x Line", None))
        self.filterset.setItemText(3, _translate("Dialog", "Line + 2 x Line", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Channel One", None))
        self.label_5.setText(_translate("Dialog", "Display", None))
        self.ch1_disp.setItemText(0, _translate("Dialog", "X", None))
        self.ch1_disp.setItemText(1, _translate("Dialog", "R", None))
        self.ch1_disp.setItemText(2, _translate("Dialog", "X noise", None))
        self.ch1_disp.setItemText(3, _translate("Dialog", "Aux in 1", None))
        self.ch1_disp.setItemText(4, _translate("Dialog", "Aux in 2", None))
        self.label_6.setText(_translate("Dialog", "Ratio", None))
        self.ch1_ratio.setItemText(0, _translate("Dialog", "none", None))
        self.ch1_ratio.setItemText(1, _translate("Dialog", "Aux In 1", None))
        self.ch1_ratio.setItemText(2, _translate("Dialog", "Aux in 2", None))
        self.label_7.setText(_translate("Dialog", "Expand", None))
        self.ch1_expand.setItemText(0, _translate("Dialog", "x1", None))
        self.ch1_expand.setItemText(1, _translate("Dialog", "x10", None))
        self.ch1_expand.setItemText(2, _translate("Dialog", "x100", None))
        self.label_8.setText(_translate("Dialog", "Offset", None))
        self.ch1_offset.setItemText(0, _translate("Dialog", "On", None))
        self.ch1_offset.setItemText(1, _translate("Dialog", "Off", None))
        self.ch1_offset.setItemText(2, _translate("Dialog", "Auto", None))
        self.ch1_offset.setItemText(3, _translate("Dialog", "Modify", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Auto", None))
        self.AutoPhaseButton.setText(_translate("Dialog", "Phase", None))
        self.AutoGainButton.setText(_translate("Dialog", "Gain", None))
        self.ReserveButton.setText(_translate("Dialog", "Reserve", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Reference", None))
        self.reference.setItemText(0, _translate("Dialog", "Phase", None))
        self.reference.setItemText(1, _translate("Dialog", "Freq", None))
        self.reference.setItemText(2, _translate("Dialog", "Ampl", None))
        self.reference.setItemText(3, _translate("Dialog", "Harm #", None))
        self.phaesplus90.setText(_translate("Dialog", "+90", None))
        self.phasemin90.setText(_translate("Dialog", "-90", None))
        self.label_13.setText(_translate("Dialog", "Trig", None))
        self.trigshape.setItemText(0, _translate("Dialog", "Sine", None))
        self.trigshape.setItemText(1, _translate("Dialog", "Pos Edge", None))
        self.trigshape.setItemText(2, _translate("Dialog", "Neg Edge", None))
        self.label_14.setText(_translate("Dialog", "Trig Source", None))
        self.trigsource.setItemText(0, _translate("Dialog", "Unlock", None))
        self.trigsource.setItemText(1, _translate("Dialog", "Internal", None))
        self.setRefbutton.setText(_translate("Dialog", "Set", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Channel Two", None))
        self.label_9.setText(_translate("Dialog", "Display", None))
        self.ch2_disp.setItemText(0, _translate("Dialog", "Y", None))
        self.ch2_disp.setItemText(1, _translate("Dialog", "Theta", None))
        self.ch2_disp.setItemText(2, _translate("Dialog", "X noise", None))
        self.ch2_disp.setItemText(3, _translate("Dialog", "Aux in 3", None))
        self.ch2_disp.setItemText(4, _translate("Dialog", "Aux in 4", None))
        self.label_10.setText(_translate("Dialog", "Ratio", None))
        self.ch2_ratio.setItemText(0, _translate("Dialog", "none", None))
        self.ch2_ratio.setItemText(1, _translate("Dialog", "Aux In 3", None))
        self.ch2_ratio.setItemText(2, _translate("Dialog", "Aux in 4", None))
        self.label_11.setText(_translate("Dialog", "Expand", None))
        self.ch2_expand.setItemText(0, _translate("Dialog", "x1", None))
        self.ch2_expand.setItemText(1, _translate("Dialog", "x10", None))
        self.ch2_expand.setItemText(2, _translate("Dialog", "x100", None))
        self.label_12.setText(_translate("Dialog", "Offset", None))
        self.ch2_offset.setItemText(0, _translate("Dialog", "On", None))
        self.ch2_offset.setItemText(1, _translate("Dialog", "Off", None))
        self.ch2_offset.setItemText(2, _translate("Dialog", "Auto", None))
        self.ch2_offset.setItemText(3, _translate("Dialog", "Modify", None))

