# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wid_Display_SR830.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(848, 276)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(270, 80, 171, 131))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 67, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.ch1_disp = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.ch1_disp.setObjectName("ch1_disp")
        self.ch1_disp.addItem("")
        self.ch1_disp.addItem("")
        self.ch1_disp.addItem("")
        self.ch1_disp.addItem("")
        self.ch1_disp.addItem("")
        self.verticalLayout_4.addWidget(self.ch1_disp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(60, 20, 68, 41))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.ch1_ratio = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.ch1_ratio.setObjectName("ch1_ratio")
        self.ch1_ratio.addItem("")
        self.ch1_ratio.addItem("")
        self.ch1_ratio.addItem("")
        self.verticalLayout_5.addWidget(self.ch1_ratio, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(110, 20, 52, 41))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.ch1_expand = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.ch1_expand.setObjectName("ch1_expand")
        self.ch1_expand.addItem("")
        self.ch1_expand.addItem("")
        self.ch1_expand.addItem("")
        self.verticalLayout_6.addWidget(self.ch1_expand, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(60, 70, 60, 41))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.ch1_offset = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        self.ch1_offset.setObjectName("ch1_offset")
        self.ch1_offset.addItem("")
        self.ch1_offset.addItem("")
        self.ch1_offset.addItem("")
        self.ch1_offset.addItem("")
        self.verticalLayout_7.addWidget(self.ch1_offset, 0, QtCore.Qt.AlignHCenter)
        self.Ref = QtWidgets.QLCDNumber(Form)
        self.Ref.setGeometry(QtCore.QRect(640, 10, 181, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.Ref.setPalette(palette)
        self.Ref.setDigitCount(7)
        self.Ref.setObjectName("Ref")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(140, 70, 120, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.reserveset = QtWidgets.QComboBox(self.groupBox_4)
        self.reserveset.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.reserveset.setObjectName("reserveset")
        self.reserveset.addItem("")
        self.reserveset.addItem("")
        self.reserveset.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 120, 131, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 66, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.input = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.input.setObjectName("input")
        self.input.addItem("")
        self.input.addItem("")
        self.input.addItem("")
        self.input.addItem("")
        self.verticalLayout.addWidget(self.input, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 40, 42, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.coupling = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.coupling.setObjectName("coupling")
        self.coupling.addItem("")
        self.coupling.addItem("")
        self.verticalLayout_2.addWidget(self.coupling, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(80, 40, 52, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.ground = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.ground.setMinimumSize(QtCore.QSize(50, 0))
        self.ground.setObjectName("ground")
        self.ground.addItem("")
        self.ground.addItem("")
        self.verticalLayout_3.addWidget(self.ground, 0, QtCore.Qt.AlignHCenter)
        self.ovldcheck = QtWidgets.QCheckBox(self.groupBox_3)
        self.ovldcheck.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.ovldcheck.setObjectName("ovldcheck")
        self.groupBox_8 = QtWidgets.QGroupBox(Form)
        self.groupBox_8.setGeometry(QtCore.QRect(440, 210, 191, 61))
        self.groupBox_8.setObjectName("groupBox_8")
        self.AutoPhaseButton = QtWidgets.QPushButton(self.groupBox_8)
        self.AutoPhaseButton.setGeometry(QtCore.QRect(10, 20, 51, 23))
        self.AutoPhaseButton.setObjectName("AutoPhaseButton")
        self.AutoGainButton = QtWidgets.QPushButton(self.groupBox_8)
        self.AutoGainButton.setGeometry(QtCore.QRect(70, 20, 51, 23))
        self.AutoGainButton.setObjectName("AutoGainButton")
        self.ReserveButton = QtWidgets.QPushButton(self.groupBox_8)
        self.ReserveButton.setGeometry(QtCore.QRect(130, 20, 51, 23))
        self.ReserveButton.setObjectName("ReserveButton")
        self.groupBox_9 = QtWidgets.QGroupBox(Form)
        self.groupBox_9.setGeometry(QtCore.QRect(640, 80, 191, 131))
        self.groupBox_9.setObjectName("groupBox_9")
        self.reference = QtWidgets.QComboBox(self.groupBox_9)
        self.reference.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.reference.setObjectName("reference")
        self.reference.addItem("")
        self.reference.addItem("")
        self.reference.addItem("")
        self.reference.addItem("")
        self.phaesplus90 = QtWidgets.QPushButton(self.groupBox_9)
        self.phaesplus90.setGeometry(QtCore.QRect(10, 50, 51, 23))
        self.phaesplus90.setObjectName("phaesplus90")
        self.phasemin90 = QtWidgets.QPushButton(self.groupBox_9)
        self.phasemin90.setGeometry(QtCore.QRect(60, 50, 51, 23))
        self.phasemin90.setObjectName("phasemin90")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 80, 74, 41))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.trigshape = QtWidgets.QComboBox(self.verticalLayoutWidget_12)
        self.trigshape.setObjectName("trigshape")
        self.trigshape.addItem("")
        self.trigshape.addItem("")
        self.trigshape.addItem("")
        self.verticalLayout_12.addWidget(self.trigshape, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(70, 80, 66, 41))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.trigsource = QtWidgets.QComboBox(self.verticalLayoutWidget_13)
        self.trigsource.setObjectName("trigsource")
        self.trigsource.addItem("")
        self.trigsource.addItem("")
        self.verticalLayout_13.addWidget(self.trigsource, 0, QtCore.Qt.AlignHCenter)
        self.setRefbutton = QtWidgets.QPushButton(self.groupBox_9)
        self.setRefbutton.setGeometry(QtCore.QRect(150, 50, 31, 23))
        self.setRefbutton.setObjectName("setRefbutton")
        self.newrefval = QtWidgets.QLineEdit(self.groupBox_9)
        self.newrefval.setGeometry(QtCore.QRect(130, 20, 51, 20))
        self.newrefval.setObjectName("newrefval")
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(450, 80, 171, 131))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 67, 41))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.ch2_disp = QtWidgets.QComboBox(self.verticalLayoutWidget_8)
        self.ch2_disp.setObjectName("ch2_disp")
        self.ch2_disp.addItem("")
        self.ch2_disp.addItem("")
        self.ch2_disp.addItem("")
        self.ch2_disp.addItem("")
        self.ch2_disp.addItem("")
        self.verticalLayout_8.addWidget(self.ch2_disp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(60, 20, 69, 41))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.ch2_ratio = QtWidgets.QComboBox(self.verticalLayoutWidget_9)
        self.ch2_ratio.setObjectName("ch2_ratio")
        self.ch2_ratio.addItem("")
        self.ch2_ratio.addItem("")
        self.ch2_ratio.addItem("")
        self.verticalLayout_9.addWidget(self.ch2_ratio, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(110, 20, 52, 41))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.ch2_expand = QtWidgets.QComboBox(self.verticalLayoutWidget_10)
        self.ch2_expand.setObjectName("ch2_expand")
        self.ch2_expand.addItem("")
        self.ch2_expand.addItem("")
        self.ch2_expand.addItem("")
        self.verticalLayout_10.addWidget(self.ch2_expand, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(60, 70, 60, 41))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.ch2_offset = QtWidgets.QComboBox(self.verticalLayoutWidget_11)
        self.ch2_offset.setObjectName("ch2_offset")
        self.ch2_offset.addItem("")
        self.ch2_offset.addItem("")
        self.ch2_offset.addItem("")
        self.ch2_offset.addItem("")
        self.verticalLayout_11.addWidget(self.ch2_offset, 0, QtCore.Qt.AlignHCenter)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 131, 101))
        self.groupBox.setObjectName("groupBox")
        self.tauval = QtWidgets.QComboBox(self.groupBox)
        self.tauval.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.tauval.setObjectName("tauval")
        self.tauval.addItem("")
        self.tauval.addItem("")
        self.tauval.addItem("")
        self.tauval.addItem("")
        self.tauval.addItem("")
        self.tauval.addItem("")
        self.tauunit = QtWidgets.QComboBox(self.groupBox)
        self.tauunit.setGeometry(QtCore.QRect(50, 20, 41, 20))
        self.tauunit.setObjectName("tauunit")
        self.tauunit.addItem("")
        self.tauunit.addItem("")
        self.tauunit.addItem("")
        self.tauunit.addItem("")
        self.slopeval = QtWidgets.QComboBox(self.groupBox)
        self.slopeval.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.slopeval.setObjectName("slopeval")
        self.slopeval.addItem("")
        self.slopeval.addItem("")
        self.slopeval.addItem("")
        self.slopeval.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(60, 50, 21, 16))
        self.label_4.setObjectName("label_4")
        self.synccheck = QtWidgets.QCheckBox(self.groupBox)
        self.synccheck.setGeometry(QtCore.QRect(10, 80, 91, 17))
        self.synccheck.setObjectName("synccheck")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(140, 10, 120, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.sensval = QtWidgets.QComboBox(self.groupBox_2)
        self.sensval.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.sensval.setObjectName("sensval")
        self.sensval.addItem("")
        self.sensval.addItem("")
        self.sensval.addItem("")
        self.sensval.addItem("")
        self.sensval.addItem("")
        self.sensval.addItem("")
        self.sensval.addItem("")
        self.sensval.addItem("")
        self.sensval.addItem("")
        self.sensunit = QtWidgets.QComboBox(self.groupBox_2)
        self.sensunit.setGeometry(QtCore.QRect(50, 20, 51, 20))
        self.sensunit.setObjectName("sensunit")
        self.sensunit.addItem("")
        self.sensunit.addItem("")
        self.sensunit.addItem("")
        self.sensunit.addItem("")
        self.Channel2 = QtWidgets.QLCDNumber(Form)
        self.Channel2.setGeometry(QtCore.QRect(450, 10, 181, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.Channel2.setPalette(palette)
        self.Channel2.setDigitCount(9)
        self.Channel2.setObjectName("Channel2")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(140, 140, 120, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.filterset = QtWidgets.QComboBox(self.groupBox_5)
        self.filterset.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.filterset.setObjectName("filterset")
        self.filterset.addItem("")
        self.filterset.addItem("")
        self.filterset.addItem("")
        self.filterset.addItem("")
        self.Channel1 = QtWidgets.QLCDNumber(Form)
        self.Channel1.setGeometry(QtCore.QRect(270, 10, 171, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.Channel1.setPalette(palette)
        self.Channel1.setDigitCount(9)
        self.Channel1.setObjectName("Channel1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_6.setTitle(_translate("Form", "Channel One"))
        self.label_5.setText(_translate("Form", "Display"))
        self.ch1_disp.setItemText(0, _translate("Form", "X"))
        self.ch1_disp.setItemText(1, _translate("Form", "R"))
        self.ch1_disp.setItemText(2, _translate("Form", "X noise"))
        self.ch1_disp.setItemText(3, _translate("Form", "Aux in 1"))
        self.ch1_disp.setItemText(4, _translate("Form", "Aux in 2"))
        self.label_6.setText(_translate("Form", "Ratio"))
        self.ch1_ratio.setItemText(0, _translate("Form", "none"))
        self.ch1_ratio.setItemText(1, _translate("Form", "Aux In 1"))
        self.ch1_ratio.setItemText(2, _translate("Form", "Aux in 2"))
        self.label_7.setText(_translate("Form", "Expand"))
        self.ch1_expand.setItemText(0, _translate("Form", "x1"))
        self.ch1_expand.setItemText(1, _translate("Form", "x10"))
        self.ch1_expand.setItemText(2, _translate("Form", "x100"))
        self.label_8.setText(_translate("Form", "Offset"))
        self.ch1_offset.setItemText(0, _translate("Form", "On"))
        self.ch1_offset.setItemText(1, _translate("Form", "Off"))
        self.ch1_offset.setItemText(2, _translate("Form", "Auto"))
        self.ch1_offset.setItemText(3, _translate("Form", "Modify"))
        self.groupBox_4.setTitle(_translate("Form", "Reserve"))
        self.reserveset.setItemText(0, _translate("Form", "High Reserve"))
        self.reserveset.setItemText(1, _translate("Form", "Normal"))
        self.reserveset.setItemText(2, _translate("Form", "Low Noise"))
        self.groupBox_3.setTitle(_translate("Form", "Signal Input"))
        self.label.setText(_translate("Form", "Input"))
        self.input.setItemText(0, _translate("Form", "A"))
        self.input.setItemText(1, _translate("Form", "A-B"))
        self.input.setItemText(2, _translate("Form", "I(10^6)"))
        self.input.setItemText(3, _translate("Form", "I(10^8)"))
        self.label_2.setText(_translate("Form", "Couple"))
        self.coupling.setItemText(0, _translate("Form", "AC"))
        self.coupling.setItemText(1, _translate("Form", "DC"))
        self.label_3.setText(_translate("Form", "Ground"))
        self.ground.setItemText(0, _translate("Form", "Float"))
        self.ground.setItemText(1, _translate("Form", "Ground"))
        self.ovldcheck.setText(_translate("Form", "OVLD"))
        self.groupBox_8.setTitle(_translate("Form", "Auto"))
        self.AutoPhaseButton.setText(_translate("Form", "Phase"))
        self.AutoGainButton.setText(_translate("Form", "Gain"))
        self.ReserveButton.setText(_translate("Form", "Reserve"))
        self.groupBox_9.setTitle(_translate("Form", "Reference"))
        self.reference.setItemText(0, _translate("Form", "Phase"))
        self.reference.setItemText(1, _translate("Form", "Freq"))
        self.reference.setItemText(2, _translate("Form", "Ampl"))
        self.reference.setItemText(3, _translate("Form", "Harm #"))
        self.phaesplus90.setText(_translate("Form", "+90"))
        self.phasemin90.setText(_translate("Form", "-90"))
        self.label_13.setText(_translate("Form", "Trig"))
        self.trigshape.setItemText(0, _translate("Form", "Sine"))
        self.trigshape.setItemText(1, _translate("Form", "Pos Edge"))
        self.trigshape.setItemText(2, _translate("Form", "Neg Edge"))
        self.label_14.setText(_translate("Form", "Trig Source"))
        self.trigsource.setItemText(0, _translate("Form", "Unlock"))
        self.trigsource.setItemText(1, _translate("Form", "Internal"))
        self.setRefbutton.setText(_translate("Form", "Set"))
        self.groupBox_7.setTitle(_translate("Form", "Channel Two"))
        self.label_9.setText(_translate("Form", "Display"))
        self.ch2_disp.setItemText(0, _translate("Form", "Y"))
        self.ch2_disp.setItemText(1, _translate("Form", "Theta"))
        self.ch2_disp.setItemText(2, _translate("Form", "X noise"))
        self.ch2_disp.setItemText(3, _translate("Form", "Aux in 3"))
        self.ch2_disp.setItemText(4, _translate("Form", "Aux in 4"))
        self.label_10.setText(_translate("Form", "Ratio"))
        self.ch2_ratio.setItemText(0, _translate("Form", "none"))
        self.ch2_ratio.setItemText(1, _translate("Form", "Aux In 3"))
        self.ch2_ratio.setItemText(2, _translate("Form", "Aux in 4"))
        self.label_11.setText(_translate("Form", "Expand"))
        self.ch2_expand.setItemText(0, _translate("Form", "x1"))
        self.ch2_expand.setItemText(1, _translate("Form", "x10"))
        self.ch2_expand.setItemText(2, _translate("Form", "x100"))
        self.label_12.setText(_translate("Form", "Offset"))
        self.ch2_offset.setItemText(0, _translate("Form", "On"))
        self.ch2_offset.setItemText(1, _translate("Form", "Off"))
        self.ch2_offset.setItemText(2, _translate("Form", "Auto"))
        self.ch2_offset.setItemText(3, _translate("Form", "Modify"))
        self.groupBox.setTitle(_translate("Form", "Time Constant"))
        self.tauval.setItemText(0, _translate("Form", "1"))
        self.tauval.setItemText(1, _translate("Form", "3"))
        self.tauval.setItemText(2, _translate("Form", "10"))
        self.tauval.setItemText(3, _translate("Form", "30"))
        self.tauval.setItemText(4, _translate("Form", "100"))
        self.tauval.setItemText(5, _translate("Form", "300"))
        self.tauunit.setItemText(0, _translate("Form", "ks"))
        self.tauunit.setItemText(1, _translate("Form", "s"))
        self.tauunit.setItemText(2, _translate("Form", "ms"))
        self.tauunit.setItemText(3, _translate("Form", "mus"))
        self.slopeval.setItemText(0, _translate("Form", "6"))
        self.slopeval.setItemText(1, _translate("Form", "12"))
        self.slopeval.setItemText(2, _translate("Form", "18"))
        self.slopeval.setItemText(3, _translate("Form", "24"))
        self.label_4.setText(_translate("Form", "db"))
        self.synccheck.setText(_translate("Form", "Sync <200 Hz"))
        self.groupBox_2.setTitle(_translate("Form", "Sensitivity"))
        self.sensval.setItemText(0, _translate("Form", "1"))
        self.sensval.setItemText(1, _translate("Form", "2"))
        self.sensval.setItemText(2, _translate("Form", "5"))
        self.sensval.setItemText(3, _translate("Form", "10"))
        self.sensval.setItemText(4, _translate("Form", "20"))
        self.sensval.setItemText(5, _translate("Form", "50"))
        self.sensval.setItemText(6, _translate("Form", "100"))
        self.sensval.setItemText(7, _translate("Form", "200"))
        self.sensval.setItemText(8, _translate("Form", "500"))
        self.sensunit.setItemText(0, _translate("Form", "V"))
        self.sensunit.setItemText(1, _translate("Form", "mV"))
        self.sensunit.setItemText(2, _translate("Form", "muV"))
        self.sensunit.setItemText(3, _translate("Form", "nV"))
        self.groupBox_5.setTitle(_translate("Form", "Filters"))
        self.filterset.setItemText(0, _translate("Form", "None"))
        self.filterset.setItemText(1, _translate("Form", "Line"))
        self.filterset.setItemText(2, _translate("Form", "2 x Line"))
        self.filterset.setItemText(3, _translate("Form", "Line + 2 x Line"))
